backup current checks
bcgov/platform-services-uptime pull request #7
Opened 2022-09-27 22:51 UTC by w8896699

2022-09-27 22:52 UTC, ShellyXueHan commented
pls get rid of the monitors that are part of our teams'.

2022-09-27 23:36 UTC, w8896699 commented
@ShellyXueHan I have applied our team filter on search results this time. Thanks for reminding me.

2022-09-28 00:01 UTC, ShellyXueHan requested changes

2022-09-28 00:01 UTC, ShellyXueHan commented on monitor-setup/checks.json
> +      "msp_script": "[{\"step_def\":\"C_OPEN_URL\",\"values\":{\"url\":\"https://registry.developer.gov.bc.ca/\"}},{\"step_def\":\"C_WAIT_FOR_ELEMENT_TEXT\",\"values\":{\"element\":\"button\",\"text\
you'll need to remove the credential for the IDIR account! Either revert commits and get rid of the history here, or you might have to update the test IDIR account credential.

2022-09-28 16:31 UTC, w8896699 commented
I delete last comment as well because credential can still be seen there. @ShellyXueHan

2022-09-28 16:41 UTC, ShellyXueHan approved these changes

2022-09-28 17:04 UTC, merged